# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hook
repos:
    -   repo: https://github.com/asottile/reorder_python_imports
        rev: v2.2.0
        hooks:
        -   id: reorder-python-imports
    -   repo: https://github.com/psf/black
        rev: stable
        hooks:
        -   id: black
            exclude: ^migrations/
            language_version: python3.7
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
        -   id: check-added-large-files
        -   id: check-docstring-first
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
        -   id: fix-encoding-pragma
        -   id: flake8
            exclude: ^migrations/
            additional_dependencies: [flake8-docstrings]
